from Actions import ActionWelcome
from Actions import FormAdmissionScore
from Actions import FormFindUniversity
from Actions import FormUniversityId
from Actions import FormUniversityAddress
from Actions import ActionAllSlotReset
from Actions import FormUniversityRank
from Actions import FormSubjects
from Actions import FormJob
from Actions import FormSalary
from Actions import FormMajorInfo
from Actions import FormCombine
from Actions import FormPriorityPoint
from Actions import FormMajorList
from Actions import FormAdmission
from Actions import ActionDefaultFallback
from Actions import FormFindMajor